"""The comment block at the top of a bundle: provenance, the main file's documentation, what the
renderer needs, and every contributing license verbatim."""

import re
import subprocess
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from onescad.licenses import License, component

_SCP_REMOTE = re.compile(r"^(?:[^@/]+@)?([^:/]+):(?!//)(.+)$")
_URL_REMOTE = re.compile(r"^[a-z+]+://(?:[^@/]+@)?([^/:]+)(?::\d+)?/(.+)$")


@dataclass(frozen=True)
class Origin:
    path: str
    remote: str | None
    commit: str
    dirty: bool


@dataclass(frozen=True)
class Header:
    version: str
    origin: Origin | None
    doc: str
    fonts: Sequence[str]
    external_files: Sequence[str]
    presets: str | None
    licenses: Sequence[License]


def normalize_remote(url: str) -> str:
    """An https URL for an scp-style, ssh or https remote, without credentials or `.git`."""
    for pattern in (_URL_REMOTE, _SCP_REMOTE):
        match = pattern.match(url.strip())
        if match:
            host, path = match.groups()
            return f"https://{host}/{path.strip('/').removesuffix('.git')}"
    return url.strip()


def _git(directory: Path, *args: str) -> str | None:
    try:
        run = subprocess.run(  # noqa: S603
            ["git", "-C", str(directory), *args],  # noqa: S607
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return run.stdout.strip()


def find_origin(main: Path) -> Origin | None:
    """Where `main` came from, or None outside a git work tree with a commit."""
    directory = main.parent
    top = _git(directory, "rev-parse", "--show-toplevel")
    commit = _git(directory, "rev-parse", "HEAD")
    if not top or not commit:
        return None
    remote = _git(directory, "remote", "get-url", "origin")
    status = _git(directory, "status", "--porcelain", "--untracked-files=no")
    return Origin(
        main.relative_to(Path(top).resolve()).as_posix(),
        normalize_remote(remote) if remote else None,
        commit,
        bool(status),
    )


def _lines(text: str) -> list[str]:
    return [f"// {line}".rstrip() for line in text.splitlines()]


def render(header: Header, roots: Sequence[Path]) -> str:
    lines = [f"// Generated by onescad {header.version}. Do not edit; edit the source instead."]
    if header.origin:
        origin = header.origin
        lines.append(f"// Source: {origin.path}")
        if origin.remote:
            lines.append(f"// Remote: {origin.remote}")
        lines.append(f"// Commit: {origin.commit}{'+dirty' if origin.dirty else ''}")
    if header.doc:
        lines += ["//", *header.doc.splitlines()]
    notes = _notes(header)
    if notes:
        lines += ["//", *notes]
    for license_file in header.licenses:
        title = f"// License: {component(license_file.path, roots)}"
        lines += ["//", title, *_lines(license_file.text())]
    return "\n".join(lines) + "\n\n"


def _notes(header: Header) -> list[str]:
    notes: list[str] = []
    if header.fonts:
        notes.append(f"// Fonts required: {', '.join(header.fonts)}")
    if header.external_files:
        notes.append(f"// External files read at render time: {', '.join(header.external_files)}")
    if header.presets:
        notes.append(
            f"// Presets: {header.presets} holds this model's Customizer presets; keep it next "
            "to this file."
        )
    return notes
