import json
from pathlib import Path

import pytest

import onescad
from helpers import HAS_OPENSCAD, write
from onescad import cli
from onescad.cli import main

MODEL = "// A model.\nuse <lib.scad>\n/* [Size] */\nw = 10; // [1:20]\ncube(helper(w));\n"
LIB = "function helper(x) = x * 2;\n"
PRESETS = {"parameterSets": {"big": {"w": "20", "$fn": "8"}}, "fileFormatVersion": "1"}


@pytest.fixture(autouse=True)
def clean_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("OPENSCADPATH", raising=False)


def model(tmp_path: Path, files: dict[str, str] | None = None) -> Path:
    return write(tmp_path / "src", files or {"m.scad": MODEL, "lib.scad": LIB})


def test_a_bundle_is_written_with_its_header(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "dist" / "m.scad"
    assert main([str(model(tmp_path)), "-o", str(out)]) == 0
    text = out.read_text()
    assert text.startswith(f"// Generated by onescad {onescad.__version__}.")
    assert "// A model." in text.split("/* [Size] */")[0]
    assert "w = 10; // [1:20]" in text
    assert "function helper(x) = x * 2;" in text
    assert capsys.readouterr().out == ""


def test_presets_are_copied_next_to_the_bundle_and_inert_keys_warn(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = model(tmp_path)
    source.with_suffix(".json").write_text(json.dumps(PRESETS))
    out = tmp_path / "dist" / "named.scad"
    assert main([str(source), "-o", str(out)]) == 0
    assert (tmp_path / "dist" / "named.json").read_text() == json.dumps(PRESETS)
    assert "// Presets: named.json" in out.read_text()
    assert "onescad: warning: m.json: preset 'big' sets '$fn'" in capsys.readouterr().err


def test_library_dirs_are_searched(tmp_path: Path) -> None:
    source = write(tmp_path / "src", {"m.scad": "use <pkg/lib.scad>\nx = helper(1);\n"})
    libs = write(tmp_path / "libs", {"pkg/lib.scad": LIB})
    out = tmp_path / "m.scad"
    assert main([str(source), "-o", str(out), "-L", str(libs.parent.parent)]) == 0
    assert "// onescad: pkg/lib.scad" in out.read_text()


def test_openscadpath_is_searched_too(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = write(tmp_path / "src", {"m.scad": "use <lib.scad>\nx = helper(1);\n"})
    write(tmp_path / "libs", {"lib.scad": LIB})
    monkeypatch.setenv("OPENSCADPATH", str(tmp_path / "libs"))
    assert main([str(source), "-o", str(tmp_path / "m.scad")]) == 0


def test_a_missing_input_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main([str(tmp_path / "nope.scad"), "-o", str(tmp_path / "o.scad")]) == 1
    err = capsys.readouterr().err
    assert err.startswith("onescad: ")
    assert "no such file" in err


def test_a_syntax_error_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = model(tmp_path, {"m.scad": "cube(;\n"})
    assert main([str(source), "-o", str(tmp_path / "o.scad")]) == 1
    assert capsys.readouterr().err.startswith("onescad: ")


def test_a_customizer_error_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = model(tmp_path, {"m.scad": "a = b + 1;\nb = 2;\n"})
    assert main([str(source), "-o", str(tmp_path / "o.scad")]) == 1
    assert capsys.readouterr().err.startswith("onescad: ")


def test_a_bundling_error_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    files = {"m.scad": "use <l.scad>\nx = f();\n", "l.scad": "$fn = 4;\nfunction f() = 1;\n"}
    assert main([str(model(tmp_path, files)), "-o", str(tmp_path / "o.scad")]) == 1
    assert "'$fn' in a used file" in capsys.readouterr().err


def test_the_output_may_not_overwrite_the_input(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = model(tmp_path)
    assert main([str(source), "-o", str(source)]) == 1
    assert source.read_text() == MODEL
    assert "overwrite the input" in capsys.readouterr().err


def test_an_unwritable_output_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    blocker = tmp_path / "file"
    blocker.write_text("")
    assert main([str(model(tmp_path)), "-o", str(blocker / "o.scad")]) == 1
    assert capsys.readouterr().err.startswith("onescad: ")


def test_usage_errors_exit_two(capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as raised:
        main([])
    assert raised.value.code == 2
    assert "onescad: error:" in capsys.readouterr().err


def test_version(capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as raised:
        main(["--version"])
    assert raised.value.code == 0
    assert capsys.readouterr().out == f"onescad {onescad.__version__}\n"


def test_messages_are_ascii(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    main([str(tmp_path / "nope.scad"), "-o", str(tmp_path / "o.scad")])
    with pytest.raises(SystemExit):
        main(["--help"])
    captured = capsys.readouterr()
    assert captured.err.isascii() and captured.out.isascii()


def test_verify_without_openscad_is_a_bundle_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str], monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(cli, "openscad_available", lambda: False)
    assert main([str(model(tmp_path)), "-o", str(tmp_path / "o.scad"), "--verify"]) == 1
    assert "--verify needs openscad" in capsys.readouterr().err


@pytest.mark.oracle
@pytest.mark.skipif(not HAS_OPENSCAD, reason="openscad is not installed")
def test_verify_passes_for_a_faithful_bundle(tmp_path: Path) -> None:
    source = model(tmp_path)
    source.with_suffix(".json").write_text(json.dumps(PRESETS))
    assert main([str(source), "-o", str(tmp_path / "dist" / "m.scad"), "--verify"]) == 0
