import subprocess
from pathlib import Path

import pytest

from onescad.header import Header, Origin, find_origin, normalize_remote, render
from onescad.licenses import License, collect, component, nearest_licenses


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        ("git@github.com:kjiwa/onescad.git", "https://github.com/kjiwa/onescad"),
        ("https://github.com/kjiwa/onescad.git", "https://github.com/kjiwa/onescad"),
        ("https://user:token@github.com/kjiwa/onescad", "https://github.com/kjiwa/onescad"),
        ("ssh://git@github.com:22/kjiwa/onescad.git", "https://github.com/kjiwa/onescad"),
        ("git://example.org/a/b.git/", "https://example.org/a/b"),
        ("/srv/repos/model", "/srv/repos/model"),
    ],
)
def test_normalize_remote(url: str, expected: str) -> None:
    assert normalize_remote(url) == expected


def git(directory: Path, *args: str) -> None:
    config = ["-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false"]
    command = ["git", "-C", str(directory), *config, *args]
    subprocess.run(command, check=True, capture_output=True)  # noqa: S603


def test_origin_outside_a_repository_is_none(tmp_path: Path) -> None:
    main = tmp_path / "m.scad"
    main.write_text("")
    assert find_origin(main) is None


def test_origin_names_path_remote_commit_and_dirtiness(tmp_path: Path) -> None:
    repo = tmp_path.resolve()
    (repo / "sub").mkdir()
    main = repo / "sub" / "m.scad"
    main.write_text("x = 1;\n")
    git(repo, "init", "-q")
    git(repo, "remote", "add", "origin", "git@github.com:kjiwa/models.git")
    git(repo, "add", ".")
    git(repo, "commit", "-q", "-m", "init")
    clean = find_origin(main)
    assert clean is not None
    assert (clean.path, clean.remote, clean.dirty) == (
        "sub/m.scad",
        "https://github.com/kjiwa/models",
        False,
    )
    assert len(clean.commit) == 40
    main.write_text("x = 2;\n")
    dirty = find_origin(main)
    assert dirty is not None and dirty.dirty


def test_origin_without_a_commit_is_none(tmp_path: Path) -> None:
    repo = tmp_path.resolve()
    main = repo / "m.scad"
    main.write_text("")
    git(repo, "init", "-q")
    assert find_origin(main) is None


def test_origin_without_a_remote_has_none(tmp_path: Path) -> None:
    repo = tmp_path.resolve()
    main = repo / "m.scad"
    main.write_text("")
    git(repo, "init", "-q")
    git(repo, "add", ".")
    git(repo, "commit", "-q", "-m", "init")
    found = find_origin(main)
    assert found is not None and found.remote is None


def test_header_lists_provenance_doc_needs_and_licenses_in_order(tmp_path: Path) -> None:
    lib = tmp_path / "lib"
    lib.mkdir()
    (lib / "LICENSE").write_text("Permission is hereby granted.\n\nNo warranty.\n")
    header = Header(
        version="1.2.3",
        origin=Origin("a/m.scad", "https://example.org/a", "abc", True),
        doc="// A model.",
        fonts=["Liberation Sans"],
        external_files=['"part.stl"'],
        presets="m.json",
        licenses=[License(lib / "LICENSE", ())],
    )
    text = render(header, [tmp_path])
    assert text.endswith("\n\n")
    assert text.splitlines() == [
        "// Generated by onescad 1.2.3. Do not edit; edit the source instead.",
        "// Source: a/m.scad",
        "// Remote: https://example.org/a",
        "// Commit: abc+dirty",
        "//",
        "// A model.",
        "//",
        "// Fonts required: Liberation Sans",
        '// External files read at render time: "part.stl"',
        "// Presets: m.json holds this model's Customizer presets; keep it next to this file.",
        "//",
        "// License: lib",
        "// Permission is hereby granted.",
        "//",
        "// No warranty.",
        "",
    ]


def test_a_bare_header_is_one_line() -> None:
    bare = Header("1", None, "", [], [], None, [])
    assert render(bare, []) == (
        "// Generated by onescad 1. Do not edit; edit the source instead.\n\n"
    )


def test_the_nearest_ancestor_license_wins(tmp_path: Path) -> None:
    (tmp_path / "LICENSE").write_text("outer")
    inner = tmp_path / "lib" / "deep"
    inner.mkdir(parents=True)
    (tmp_path / "lib" / "LICENSE-MIT").write_text("mit")
    (tmp_path / "lib" / "COPYING").write_text("copying")
    (tmp_path / "lib" / "README").write_text("not a license")
    assert [p.name for p in nearest_licenses(inner / "a.scad")] == ["COPYING", "LICENSE-MIT"]
    assert [p.name for p in nearest_licenses(tmp_path / "b.scad")] == ["LICENSE"]


def test_collect_groups_files_by_license_and_reports_unlicensed(tmp_path: Path) -> None:
    (tmp_path / "lib").mkdir()
    (tmp_path / "lib" / "LICENSE").write_text("x")
    a, b = tmp_path / "lib" / "a.scad", tmp_path / "lib" / "b.scad"
    c = tmp_path / "c.scad"
    found, unlicensed = collect([a, b, c])
    assert [(f.path.name, f.covers) for f in found] == [("LICENSE", (a, b))]
    assert unlicensed == [c]


def test_component_is_relative_to_the_first_containing_root(tmp_path: Path) -> None:
    root = tmp_path / "repo"
    assert component(root / "lib" / "BOSL2" / "LICENSE", [root]) == "lib/BOSL2"
    assert component(root / "LICENSE", [root]) == "repo"
    assert component(Path("/elsewhere/pkg/LICENSE"), [root]) == "pkg"
